name: Run Tests on Dispatch

on:
  repository_dispatch:
    types:
      - run-tests
  workflow_dispatch: # Allows manual trigger

concurrency:
  group: run-tests-${{ github.event.client_payload.branch || 'manual-run' }}
  cancel-in-progress: true # Cancel previous runs for the same branch or manual runs

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20' # Adjust to your required Go version

      - name: Run Tests
        run: echo "Setting up environment"
       
